### ISSUE TITLE
How do I use javafx to achieve this heatmap effect?

### ISSUE THREAD

**Issue by donnie0915** [HanSolo/FxHeatMap#2]
https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian
![image](https://user-images.githubusercontent.com/5294336/216817865-8e47621f-ae92-404c-bdda-a4d23cabc0ca.png)

**Comment by HanSolo** [comment]
Just use a simple GridPane with Labels and set the background for each Label according to the value…that’s it
